[project]
package = "bumpwright"
public_roots = ["./bumpwright/"]

[ignore]
paths = ["tests/**", "docs/**", "build/**", ".venv/**"]

[rules]
return_type_change = "minor"  # or "major"

[analysers]
cli = true
