name: bumpwright version check

on:
  workflow_dispatch:

jobs:
  decide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install bumpwright
        run: pip install bumpwright
      - name: Suggest next version
        run: |
          bumpwright bump --decide --format md
