name: bumpwright auto bump

on:
  push:
    branches:
      - master

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install bumpwright
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
      - name: Bump version and update changelog
        run: |
          bumpwright bump --decide --changelog CHANGELOG.md --commit --tag
      - name: Push changes
        run: git push origin HEAD --follow-tags
