name: Docs

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build Sphinx HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: 'pip'

      - name: Install project (docs + dev extras)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install -e ".[docs,dev]"

      - name: Generate badges into Sphinx _static
        run: |
          mkdir -p docs/_static/badges
          python .github/scripts/generate_badges.py docs/_static/badges

      - name: Build HTML
        working-directory: docs
        run: |
          # Common Sphinx layouts: docs/source -> build/html OR docs/ -> build
          if [ -d "source" ]; then
            sphinx-build -b html source build/html
          else
            sphinx-build -b html . build
          fi

      - name: Upload artifact (for Pages)
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
